name: daily-report

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Run Internship Notifier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 139
          install-chromedriver: true
          install-dependencies: true

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Internship Notifier
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD:  ${{ secrets.USER_PASSWORD }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: python internship_notifier.py

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin main
          git pull --rebase origin main
          git commit --allow-empty -am "Automated commit from GitHub Actions"
          git push origin main