name: daily-report

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Run Internship Notifier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          install-chromedriver: true

      - name: Run Internship Notifier
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD:  ${{ secrets.USER_PASSWORD }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: python internship_notifier.py

